envs:
  - name: RemoteEnv
    n_envs: 5000
    data_source: primitive_skill
    seed: [0, 5000]
    max_turns: 5
    response_length_per_turn: 1024
    config:
      base_urls: "http://localhost:8000"
      timeout: 120
      retries: 3
      env_id: AlignTwoCube
      prompt_format: wm
      max_actions_per_step: 2
      action_sep: "|"
      render_mode: vision
      format_reward: 0.1
      success_reward: 10.0

  - name: RemoteEnv
    n_envs: 5000
    data_source: primitive_skill
    seed: [0, 5000]
    max_turns: 5
    response_length_per_turn: 1024
    config:
      base_urls: "http://localhost:8000"
      timeout: 120
      retries: 3
      env_id: PlaceTwoCube
      prompt_format: wm
      max_actions_per_step: 2
      action_sep: "|"
      render_mode: vision
      format_reward: 0.1
      success_reward: 10.0

  - name: RemoteEnv
    n_envs: 5000
    data_source: primitive_skill
    seed: [0, 5000]
    max_turns: 5
    response_length_per_turn: 1024
    config:
      base_urls: "http://localhost:8000"
      timeout: 120
      retries: 3
      env_id: StackThreeCube
      prompt_format: wm
      max_actions_per_step: 2
      action_sep: "|"
      render_mode: vision
      format_reward: 0.1
      success_reward: 10.0

  - name: RemoteEnv
    n_envs: 5000
    data_source: primitive_skill
    seed: [0, 5000]
    max_turns: 5
    response_length_per_turn: 1024
    config:
      base_urls: "http://localhost:8000"
      timeout: 120
      retries: 3
      env_id: PutAppleInDrawer
      prompt_format: wm
      max_actions_per_step: 2
      action_sep: "|"
      render_mode: vision
      format_reward: 0.1
      success_reward: 10.0
