# Original Sokoban environment and reward scale used by VAGEN.
envs:
  - name: Sokoban # registered env name
    n_envs: 10000 
    data_source: sokoban # nickname for logging
    seed: [1,10000,1] # sample n_env seeds from seed[0] to seed[1] with each seed repeat at most seed[2] times
    max_turns: 5
    response_length_per_turn: 512
    max_env_response_per_turn: 256
    config:
      render_mode: vision
      format_reward: 0.02
      min_solution_steps: [1,5]
      
