fileroot: ${oc.env:HOME}/projects/vagen

envs:
  - name: RemoteEnv
    n_envs: 51
    data_source: eb_alfred
    tag_id: eb_alfred_train_base
    seed: [0, 51, 1]
    max_turns: 30
    concat_multi_turn: false
    config:
      base_urls:
        - "http://localhost:8000"
      timeout: 600
      eval_set: base
      obs_image_size: 500
      max_turns: 30
      max_actions_per_step: 20
      max_env_steps: 30
      action_sep: "|"
      prompt_format: free_think
      use_example_in_sys_prompt: true
      format_reward: 0.1
      success_reward: 1.0
    chat_config:
      temperature: 0
      max_tokens: 2048
      top_p: 1.0
      stop: ["<|diff_marker|>"]

  - name: RemoteEnv
    n_envs: 50
    data_source: eb_alfred
    tag_id: eb_alfred_train_complex
    seed: [0, 50, 1]
    max_turns: 30
    concat_multi_turn: false
    config:
      base_urls:
        - "http://localhost:8000"
      timeout: 600
      eval_set: complex_instruction
      obs_image_size: 500
      max_turns: 30
      max_actions_per_step: 20
      max_env_steps: 30
      action_sep: "|"
      prompt_format: free_think
      use_example_in_sys_prompt: true
      format_reward: 0.1
      success_reward: 1.0
    chat_config:
      temperature: 0
      max_tokens: 2048
      top_p: 1.0
      stop: ["<|diff_marker|>"]

  - name: RemoteEnv
    n_envs: 50
    data_source: eb_alfred
    tag_id: eb_alfred_train_visual
    seed: [0, 50, 1]
    max_turns: 30
    concat_multi_turn: false
    config:
      base_urls:
        - "http://localhost:8000"
      timeout: 600
      eval_set: visual_appearance
      obs_image_size: 500
      max_turns: 30
      max_actions_per_step: 20
      max_env_steps: 30
      action_sep: "|"
      prompt_format: free_think
      use_example_in_sys_prompt: true
      format_reward: 0.1
      success_reward: 1.0
    chat_config:
      temperature: 0
      max_tokens: 2048
      top_p: 1.0
      stop: ["<|diff_marker|>"]

experiment:
  dump_dir: ${fileroot}/rollouts/eval_eb_alfred
  default_max_turns: 30

run:
  backend: "sglang"
  base_seed: 0
  max_concurrent_jobs: 4
  resume: skip_completed
  live_summary: true

backends:
  openai:
    api_key: ""               # or env OPENAI_API_KEY
    base_url: null
    model: "gpt-4o"
    max_concurrency: 2
    max_retries: 6
    min_backoff: 0.5
    max_backoff: 8.0

  sglang:
    base_url: "http://127.0.0.1:30000/v1"
    api_key: "EMPTY"
    model: "/home/march/workspace/Yaning/models/EPL-Only-Model_EB-Alfred"
    max_concurrency: 2
    max_retries: 6
    min_backoff: 0.5
    max_backoff: 8.0

  claude:
    api_key: ""
    base_url: null
    model: "claude-3-5-sonnet-latest"
    max_concurrency: 2
    max_retries: 6
    min_backoff: 0.5
    max_backoff: 8.0
