envs:
  - name: ScannetAG 
    data_source: action_generation_0_2
    seed: [0,327,1]
    n_envs: 327
    max_turns: 1
    response_length_per_turn: 2048 
    config:
      jsonl_path: ${oc.env:HOME}/projects/viewsuite/data/viewsuite_5k/action_gen_train_0_2_filter.jsonl
      image_size: [512,512]
      eval_mode: false
      format_reward: 0.1
      answer_reward: 0.9

  - name: ScannetAG 
    data_source: action_generation_3_5
    seed: [0,1225,1]
    n_envs: 1225
    max_turns: 1
    response_length_per_turn: 2048 
    config:
      jsonl_path: ${oc.env:HOME}/projects/viewsuite/data/viewsuite_5k/action_gen_train_3_5_filter.jsonl
      image_size: [512,512]
      eval_mode: false
      format_reward: 0.1
      answer_reward: 0.9
      


      
