envs:
  - name: Sokoban # registered env name
    n_envs: 10000
    data_source: sokoban # nickname for logging
    seed: [1,10000,1] # sample n_env seeds from seed[0] to seed[1] with each seed repeat at most seed[2] times
    max_turns: 5 # max number of interaction turns per episode
    response_length_per_turn: 512 # max response length per turn
    config: # env-specific config
      render_mode: vision
      min_solution_steps: [1,5]
      prompt_format: free_wm
